An exception occurred

User ID <%= user.try(&.id) || "(none)" %>

Here's the backtrace
<%= exception.inspect_with_backtrace %>
